# 
#  Copyright (C) 2025 wisevision
#
#  SPDX-License-Identifier: MPL-2.0
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

version: '3.8'

services:
  influxdb:
    image: influxdb:1.8  
    ports:
      - "8086:8086"  
    volumes:
      - influxdb_data:/var/lib/influxdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  zenoh_router:
    build:
      context: ./docker-files/zenoh-influxdb-docker
      dockerfile: Dockerfile
    depends_on:
      influxdb:
        condition: service_healthy
    init: true
    network_mode: host
    volumes:
      - ./zenoh_router.json5:/root/.zenoh/zenoh_router.json5
    command: ["-c", "/root/.zenoh/zenoh_router.json5"]

  wisevision-dashboard-backend:
    extends:
      file: ./src/wisevision_dashboard/docker-compose.yml
      service: backend
      
  wisevision-frontend:
    extends:
      file: ./src/wisevision_dashboard/docker-compose.yml
      service: client

  wisevision_launcher:
    build:
      context: .
      dockerfile: docker-files/wisevision-launch/Dockerfile
    env_file:
      - .env
    network_mode: host
    volumes:
      - ./ros_params.yaml:/root/wisevision_proj_ws/src/ros_params.yaml

volumes:
  influxdb_data: