version: '3.8'

services:
  influxdb:
    image: influxdb:1.8  
    ports:
      - "8086:8086"  
    volumes:
      - influxdb_data:/var/lib/influxdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  zenoh:
    build:
      context: ./docker-files/zenoh-influxdb-docker 
      dockerfile: Dockerfile
    init: true 
    network_mode: host
    volumes:
      - ./zenoh.json5:/root/.zenoh/zenoh.json5 
    command: ["-c", "/root/.zenoh/zenoh.json5"]
    depends_on:
      influxdb:
        condition: service_healthy  # Wait until InfluxDB is healthy
      
  ros2_automatic_action_execution:
    extends:
      file: ./src/ros2_automatic_action_execution/docker-compose.yml
      service: ros2_automatic_action_execution 
      
  ros2_black_box:
    extends:
      file: ./src/ros2_black_box/docker-compose.yml
      service: ros2_black_box
    volumes:
      - ./config.json:/root/ros2_black_box_ws/config.json 

  wisevision-dashboard:
    extends:
      file: ./src/wisevision-dashboard/docker-compose.yml
      service: backend
  wisevision_gps_tools:
    extends:
      file: ./src/wisevision_gps_tools/docker-compose.yml
      service: wisevision_gps_tools

volumes:
  influxdb_data: