name: Build and Push Multi-Architecture Docker Image ros_with_wisevision_msgs_wisevision_core_and_grpc:humble

on:
  workflow_run:
    workflows:
      - Build and Push Image Base
    types:
      - completed

jobs:
  build-and-push:
    runs-on: self-hosted

    container:
      image: ubuntu:22.04
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
      
    - name: Install Docker CLI
      run: |
        apt-get update
        apt-get install -y docker.io

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image for multiple architectures
      run: |
        cd ./docker-files/wisevision-base-and-grpc-image
        docker buildx build --platform linux/amd64,linux/arm64 \
          --tag ${{ secrets.DOCKER_HUB_USERNAME }}/ros_with_wisevision_msgs_wisevision_core_and_grpc:humble --push .
